# Generated by Django 5.1.2 on 2026-02-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_delete_samplemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='titel',
            new_name='title',
        ),
    ]
