# Generated by Django 5.1.2 on 2026-03-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_review_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
